const colors = require('tailwindcss/colors');

module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  safelist: [
    "bg-blue-600",
    "to-indigo-600",
    "from-blue-600",
    "from-slate-50",
    "via-blue-50",
    "to-indigo-100",
    "bg-white/80",
    "border-b",
    "border-slate-200/50",
    "shadow-sm",
    "text-xl",
    "font-bold",
    "text-slate-800",
    "tracking-tight",
    "text-sm",
    "text-slate-500",
    "bg-gradient-to-br",
    "rounded-xl",
    "shadow-lg",
    "h-6",
    "w-6",
    "rounded-full",
    "bg-white",
    "text-white",
    "bg-gradient-to-r",
    "rounded-2xl",
    "rounded-br-md",
    "shadow-lg",
    "bg-white",
    "text-slate-800",
    "rounded-bl-md",
    "shadow-sm",
    "border",
    "border-slate-200/50",
    "px-5",
    "py-4",
    "transition-all",
    "duration-200",
    "hover:shadow-md",
    "text-base",
    "leading-relaxed",
    "text-xs",
    "mt-2",
    "text-blue-100",
    "text-slate-400",
    "bg-gradient-to-br",
    "from-slate-600",
    "to-slate-700",
    "shadow-md",
    "animate-fadeIn",
    "animate-bounce",
    "bg-white",
    "text-slate-800",
    "rounded-2xl",
    "rounded-bl-md",
    "shadow-sm",
    "border",
    "border-slate-200/50",
    "px-5",
    "py-4",
    "flex",
    "gap-1",
    "w-2",
    "h-2",
    "bg-slate-400",
    "rounded-full",
    "animate-bounce",
    "text-sm",
    "text-slate-500",
    "ml-2",
    "fixed",
    "bottom-0",
    "left-0",
    "right-0",
    "bg-white/80",
    "backdrop-blur-md",
    "border-t",
    "border-slate-200/50",
    "shadow-lg",
    "max-w-4xl",
    "mx-auto",
    "p-4",
    "flex-1",
    "relative",
    "w-full",
    "px-4",
    "py-3",
    "pr-12",
    "rounded-xl",
    "border",
    "border-slate-300",
    "focus:border-blue-500",
    "focus:ring-2",
    "focus:ring-blue-500/20",
    "bg-white",
    "shadow-sm",
    "resize-none",
    "transition-all",
    "duration-200",
    "text-base",
    "leading-relaxed",
    "max-h-32",
    "absolute",
    "right-3",
    "bottom-3",
    "text-xs",
    "text-slate-400",
    "px-6",
    "py-3",
    "bg-gradient-to-r",
    "from-blue-600",
    "to-indigo-600",
    "text-white",
    "font-medium",
    "rounded-xl",
    "shadow-lg",
    "hover:shadow-xl",
    "disabled:opacity-50",
    "disabled:cursor-not-allowed",
    "transition-all",
    "duration-200",
    "hover:scale-105",
    "active:scale-95",
    "flex",
    "items-center",
    "gap-2",
    "w-4",
    "h-4",
    "border-2",
    "border-white/30",
    "border-t-white",
    "rounded-full",
    "animate-spin",
    "text-xs",
    "text-slate-500",
    "mt-2",
    "text-center",
    // Add any other classes you use!
  ],
  theme: {
    extend: {
      colors: {
        blue: colors.blue,
        indigo: colors.indigo,
        slate: colors.slate,
        white: colors.white,
        red: colors.red,
        green: colors.green,
        gray: colors.gray,
        yellow: colors.yellow,
      },
      animation: {
        'fade-in': 'fadeIn 0.5s ease-in-out',
        'slide-up': 'slideUp 0.3s ease-out',
        'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'fadeIn': 'fadeIn 0.3s ease-out',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0', transform: 'translateY(10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        slideUp: {
          '0%': { transform: 'translateY(10px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        }
      },
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
  ],
}
